<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="9" failed="1" total="10" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Rediff Mail Execution Suite" duration-ms="23048" started-at="2014-11-14T06:20:21Z" finished-at="2014-11-14T06:20:44Z">
    <groups>
      <group name="Selenium">
        <method signature="HomePageTest.verifyBrokenLink()[pri:0, instance:com.rediff.testcases.HomePageTest@87bd1c]" name="verifyBrokenLink" class="com.rediff.testcases.HomePageTest"/>
        <method signature="LoginTest.blankUserNameBlankPasswordLoginTest()[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="blankUserNameBlankPasswordLoginTest" class="com.rediff.testcases.LoginTest"/>
        <method signature="LoginTest.blankUserNameRightPasswordLoginTest(java.util.Hashtable)[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="blankUserNameRightPasswordLoginTest" class="com.rediff.testcases.LoginTest"/>
        <method signature="LoginTest.blankUserNameWrongPasswordLoginTest()[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="blankUserNameWrongPasswordLoginTest" class="com.rediff.testcases.LoginTest"/>
        <method signature="LoginTest.rightUserNameBlankPasswordLoginTest()[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="rightUserNameBlankPasswordLoginTest" class="com.rediff.testcases.LoginTest"/>
        <method signature="LoginTest.rightUserNameWrongPasswordLoginTest()[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="rightUserNameWrongPasswordLoginTest" class="com.rediff.testcases.LoginTest"/>
        <method signature="LoginTest.sucessfullLoginTest(java.util.Hashtable)[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="sucessfullLoginTest" class="com.rediff.testcases.LoginTest"/>
        <method signature="LoginTest.wrongUserNameBlankPasswordLoginTest()[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="wrongUserNameBlankPasswordLoginTest" class="com.rediff.testcases.LoginTest"/>
        <method signature="LoginTest.wrongUserNameRightPasswordLoginTest()[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="wrongUserNameRightPasswordLoginTest" class="com.rediff.testcases.LoginTest"/>
        <method signature="LoginTest.wrongUserNameWrongPasswordLoginTest()[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="wrongUserNameWrongPasswordLoginTest" class="com.rediff.testcases.LoginTest"/>
      </group> <!-- Selenium -->
    </groups>
    <test name="Rediff WebSite Testing" duration-ms="23048" started-at="2014-11-14T06:20:21Z" finished-at="2014-11-14T06:20:44Z">
      <class name="com.rediff.testcases.LoginTest">
        <test-method status="PASS" signature="before()[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="before" is-config="true" duration-ms="45" started-at="2014-11-14T11:50:21Z" finished-at="2014-11-14T11:50:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method status="FAIL" signature="classSetUp(java.lang.String)[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="classSetUp" is-config="true" duration-ms="0" started-at="2014-11-14T11:50:22Z" finished-at="2014-11-14T11:50:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[localhost]]>
              </value>
            </param>
          </params>
          <exception class="com.framework.exception.MyException">
            <message>
              <![CDATA[Error in connecting with Remote WebDriverorg.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.42.1', revision: '68b415adb11acca4286be45124325cc36cfc4a51', time: '2014-05-29 09:21:55'
System info: host: 'SDGL691', ip: '10.20.20.29', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_67'
Driver info: driver.version: RemoteWebDriver]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.framework.exception.MyException: Error in connecting with Remote WebDriverorg.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.42.1', revision: '68b415adb11acca4286be45124325cc36cfc4a51', time: '2014-05-29 09:21:55'
System info: host: 'SDGL691', ip: '10.20.20.29', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_67'
Driver info: driver.version: RemoteWebDriver
	at com.framework.testtemplate.TestBase.startWebDriver(TestBase.java:116)
	at com.rediff.testcases.LoginTest.classSetUp(LoginTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- com.framework.exception.MyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classSetUp -->
        <test-method status="SKIP" signature="LoginTestSetUp(java.lang.reflect.Method)[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="LoginTestSetUp" is-config="true" duration-ms="0" started-at="2014-11-14T11:50:39Z" finished-at="2014-11-14T11:50:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTestSetUp -->
        <test-method status="SKIP" signature="blankUserNameBlankPasswordLoginTest()[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="blankUserNameBlankPasswordLoginTest" duration-ms="9" started-at="2014-11-14T11:50:39Z" finished-at="2014-11-14T11:50:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- blankUserNameBlankPasswordLoginTest -->
        <test-method status="FAIL" signature="TearDown(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="TearDown" is-config="true" duration-ms="0" started-at="2014-11-14T11:50:39Z" finished-at="2014-11-14T11:50:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=blankUserNameBlankPasswordLoginTest status=SKIP method=LoginTest.blankUserNameBlankPasswordLoginTest()[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.rediff.testcases.LoginTest.blankUserNameBlankPasswordLoginTest() throws com.framework.exception.MyException]]>
              </value>
            </param>
          </params>
          <exception class="com.framework.exception.MyException">
            <message>
              <![CDATA[TestBase -> embedScreenShotIntoReport() - null]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.framework.exception.MyException: TestBase -> embedScreenShotIntoReport() - null
	at com.framework.report.CaptureBrowserScreenShot.embedScreenShotIntoReport(CaptureBrowserScreenShot.java:88)
	at com.framework.testtemplate.TestBase.TearDown(TestBase.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- com.framework.exception.MyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="SKIP" signature="LoginTestSetUp(java.lang.reflect.Method)[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="LoginTestSetUp" is-config="true" duration-ms="0" started-at="2014-11-14T11:50:43Z" finished-at="2014-11-14T11:50:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTestSetUp -->
        <test-method status="SKIP" signature="blankUserNameRightPasswordLoginTest(java.util.Hashtable)[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="blankUserNameRightPasswordLoginTest" duration-ms="3" started-at="2014-11-14T11:50:43Z" data-provider="readData" finished-at="2014-11-14T11:50:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=ancd@gmail.com, Password=affirm123}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- blankUserNameRightPasswordLoginTest -->
        <test-method status="FAIL" signature="TearDown(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="TearDown" is-config="true" duration-ms="0" started-at="2014-11-14T11:50:43Z" finished-at="2014-11-14T11:50:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=blankUserNameRightPasswordLoginTest status=SKIP method=LoginTest.blankUserNameRightPasswordLoginTest(java.util.Hashtable)[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.rediff.testcases.LoginTest.blankUserNameRightPasswordLoginTest(java.util.Hashtable) throws com.framework.exception.MyException]]>
              </value>
            </param>
          </params>
          <exception class="com.framework.exception.MyException">
            <message>
              <![CDATA[TestBase -> embedScreenShotIntoReport() - null]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.framework.exception.MyException: TestBase -> embedScreenShotIntoReport() - null
	at com.framework.report.CaptureBrowserScreenShot.embedScreenShotIntoReport(CaptureBrowserScreenShot.java:88)
	at com.framework.testtemplate.TestBase.TearDown(TestBase.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- com.framework.exception.MyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="SKIP" signature="LoginTestSetUp(java.lang.reflect.Method)[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="LoginTestSetUp" is-config="true" duration-ms="0" started-at="2014-11-14T11:50:44Z" finished-at="2014-11-14T11:50:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTestSetUp -->
        <test-method status="SKIP" signature="blankUserNameWrongPasswordLoginTest()[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="blankUserNameWrongPasswordLoginTest" duration-ms="4" started-at="2014-11-14T11:50:44Z" finished-at="2014-11-14T11:50:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- blankUserNameWrongPasswordLoginTest -->
        <test-method status="FAIL" signature="TearDown(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="TearDown" is-config="true" duration-ms="0" started-at="2014-11-14T11:50:44Z" finished-at="2014-11-14T11:50:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=blankUserNameWrongPasswordLoginTest status=SKIP method=LoginTest.blankUserNameWrongPasswordLoginTest()[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.rediff.testcases.LoginTest.blankUserNameWrongPasswordLoginTest() throws com.framework.exception.MyException]]>
              </value>
            </param>
          </params>
          <exception class="com.framework.exception.MyException">
            <message>
              <![CDATA[TestBase -> embedScreenShotIntoReport() - null]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.framework.exception.MyException: TestBase -> embedScreenShotIntoReport() - null
	at com.framework.report.CaptureBrowserScreenShot.embedScreenShotIntoReport(CaptureBrowserScreenShot.java:88)
	at com.framework.testtemplate.TestBase.TearDown(TestBase.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- com.framework.exception.MyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="FAIL" signature="rightUserNameBlankPasswordLoginTest()[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="rightUserNameBlankPasswordLoginTest" duration-ms="9" started-at="2014-11-14T11:50:44Z" data-provider="readData" finished-at="2014-11-14T11:50:44Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
The data provider is trying to pass 1 parameters but the method com.rediff.testcases.LoginTest#rightUserNameBlankPasswordLoginTest takes 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 1 parameters but the method com.rediff.testcases.LoginTest#rightUserNameBlankPasswordLoginTest takes 0
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1337)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1225)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rightUserNameBlankPasswordLoginTest -->
        <test-method status="SKIP" signature="LoginTestSetUp(java.lang.reflect.Method)[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="LoginTestSetUp" is-config="true" duration-ms="0" started-at="2014-11-14T11:50:44Z" finished-at="2014-11-14T11:50:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTestSetUp -->
        <test-method status="SKIP" signature="rightUserNameWrongPasswordLoginTest()[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="rightUserNameWrongPasswordLoginTest" duration-ms="2" started-at="2014-11-14T11:50:44Z" finished-at="2014-11-14T11:50:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rightUserNameWrongPasswordLoginTest -->
        <test-method status="FAIL" signature="TearDown(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="TearDown" is-config="true" duration-ms="0" started-at="2014-11-14T11:50:44Z" finished-at="2014-11-14T11:50:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=rightUserNameWrongPasswordLoginTest status=SKIP method=LoginTest.rightUserNameWrongPasswordLoginTest()[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.rediff.testcases.LoginTest.rightUserNameWrongPasswordLoginTest() throws com.framework.exception.MyException]]>
              </value>
            </param>
          </params>
          <exception class="com.framework.exception.MyException">
            <message>
              <![CDATA[TestBase -> embedScreenShotIntoReport() - null]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.framework.exception.MyException: TestBase -> embedScreenShotIntoReport() - null
	at com.framework.report.CaptureBrowserScreenShot.embedScreenShotIntoReport(CaptureBrowserScreenShot.java:88)
	at com.framework.testtemplate.TestBase.TearDown(TestBase.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- com.framework.exception.MyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="SKIP" signature="LoginTestSetUp(java.lang.reflect.Method)[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="LoginTestSetUp" is-config="true" duration-ms="0" started-at="2014-11-14T11:50:44Z" finished-at="2014-11-14T11:50:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTestSetUp -->
        <test-method status="SKIP" signature="sucessfullLoginTest(java.util.Hashtable)[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="sucessfullLoginTest" duration-ms="2" started-at="2014-11-14T11:50:44Z" data-provider="readData" finished-at="2014-11-14T11:50:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=ancd@gmail.com, Password=affirm123, Runmode=Y, Flag=Y}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sucessfullLoginTest -->
        <test-method status="FAIL" signature="TearDown(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="TearDown" is-config="true" duration-ms="0" started-at="2014-11-14T11:50:44Z" finished-at="2014-11-14T11:50:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=sucessfullLoginTest status=SKIP method=LoginTest.sucessfullLoginTest(java.util.Hashtable)[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.rediff.testcases.LoginTest.sucessfullLoginTest(java.util.Hashtable) throws com.framework.exception.MyException]]>
              </value>
            </param>
          </params>
          <exception class="com.framework.exception.MyException">
            <message>
              <![CDATA[TestBase -> embedScreenShotIntoReport() - null]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.framework.exception.MyException: TestBase -> embedScreenShotIntoReport() - null
	at com.framework.report.CaptureBrowserScreenShot.embedScreenShotIntoReport(CaptureBrowserScreenShot.java:88)
	at com.framework.testtemplate.TestBase.TearDown(TestBase.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- com.framework.exception.MyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="SKIP" signature="LoginTestSetUp(java.lang.reflect.Method)[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="LoginTestSetUp" is-config="true" duration-ms="0" started-at="2014-11-14T11:50:44Z" finished-at="2014-11-14T11:50:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTestSetUp -->
        <test-method status="SKIP" signature="wrongUserNameBlankPasswordLoginTest()[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="wrongUserNameBlankPasswordLoginTest" duration-ms="2" started-at="2014-11-14T11:50:44Z" finished-at="2014-11-14T11:50:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wrongUserNameBlankPasswordLoginTest -->
        <test-method status="FAIL" signature="TearDown(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="TearDown" is-config="true" duration-ms="0" started-at="2014-11-14T11:50:44Z" finished-at="2014-11-14T11:50:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=wrongUserNameBlankPasswordLoginTest status=SKIP method=LoginTest.wrongUserNameBlankPasswordLoginTest()[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.rediff.testcases.LoginTest.wrongUserNameBlankPasswordLoginTest() throws com.framework.exception.MyException]]>
              </value>
            </param>
          </params>
          <exception class="com.framework.exception.MyException">
            <message>
              <![CDATA[TestBase -> embedScreenShotIntoReport() - null]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.framework.exception.MyException: TestBase -> embedScreenShotIntoReport() - null
	at com.framework.report.CaptureBrowserScreenShot.embedScreenShotIntoReport(CaptureBrowserScreenShot.java:88)
	at com.framework.testtemplate.TestBase.TearDown(TestBase.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- com.framework.exception.MyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="SKIP" signature="LoginTestSetUp(java.lang.reflect.Method)[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="LoginTestSetUp" is-config="true" duration-ms="0" started-at="2014-11-14T11:50:44Z" finished-at="2014-11-14T11:50:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTestSetUp -->
        <test-method status="SKIP" signature="wrongUserNameRightPasswordLoginTest()[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="wrongUserNameRightPasswordLoginTest" duration-ms="2" started-at="2014-11-14T11:50:44Z" finished-at="2014-11-14T11:50:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wrongUserNameRightPasswordLoginTest -->
        <test-method status="FAIL" signature="TearDown(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="TearDown" is-config="true" duration-ms="0" started-at="2014-11-14T11:50:44Z" finished-at="2014-11-14T11:50:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=wrongUserNameRightPasswordLoginTest status=SKIP method=LoginTest.wrongUserNameRightPasswordLoginTest()[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.rediff.testcases.LoginTest.wrongUserNameRightPasswordLoginTest() throws com.framework.exception.MyException]]>
              </value>
            </param>
          </params>
          <exception class="com.framework.exception.MyException">
            <message>
              <![CDATA[TestBase -> embedScreenShotIntoReport() - null]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.framework.exception.MyException: TestBase -> embedScreenShotIntoReport() - null
	at com.framework.report.CaptureBrowserScreenShot.embedScreenShotIntoReport(CaptureBrowserScreenShot.java:88)
	at com.framework.testtemplate.TestBase.TearDown(TestBase.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- com.framework.exception.MyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="SKIP" signature="LoginTestSetUp(java.lang.reflect.Method)[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="LoginTestSetUp" is-config="true" duration-ms="0" started-at="2014-11-14T11:50:44Z" finished-at="2014-11-14T11:50:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTestSetUp -->
        <test-method status="SKIP" signature="wrongUserNameWrongPasswordLoginTest()[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="wrongUserNameWrongPasswordLoginTest" duration-ms="3" started-at="2014-11-14T11:50:44Z" finished-at="2014-11-14T11:50:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wrongUserNameWrongPasswordLoginTest -->
        <test-method status="FAIL" signature="TearDown(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="TearDown" is-config="true" duration-ms="0" started-at="2014-11-14T11:50:44Z" finished-at="2014-11-14T11:50:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=wrongUserNameWrongPasswordLoginTest status=SKIP method=LoginTest.wrongUserNameWrongPasswordLoginTest()[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.rediff.testcases.LoginTest.wrongUserNameWrongPasswordLoginTest() throws com.framework.exception.MyException]]>
              </value>
            </param>
          </params>
          <exception class="com.framework.exception.MyException">
            <message>
              <![CDATA[TestBase -> embedScreenShotIntoReport() - null]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.framework.exception.MyException: TestBase -> embedScreenShotIntoReport() - null
	at com.framework.report.CaptureBrowserScreenShot.embedScreenShotIntoReport(CaptureBrowserScreenShot.java:88)
	at com.framework.testtemplate.TestBase.TearDown(TestBase.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- com.framework.exception.MyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="PASS" signature="stopDriver()[pri:0, instance:com.rediff.testcases.LoginTest@24c6ab]" name="stopDriver" is-config="true" duration-ms="0" started-at="2014-11-14T11:50:44Z" finished-at="2014-11-14T11:50:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stopDriver -->
      </class> <!-- com.rediff.testcases.LoginTest -->
      <class name="com.rediff.testcases.HomePageTest">
        <test-method status="FAIL" signature="classSetUp(java.lang.String)[pri:0, instance:com.rediff.testcases.HomePageTest@87bd1c]" name="classSetUp" is-config="true" duration-ms="0" started-at="2014-11-14T11:50:22Z" finished-at="2014-11-14T11:50:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[localhost]]>
              </value>
            </param>
          </params>
          <exception class="com.framework.exception.MyException">
            <message>
              <![CDATA[Error in connecting with Remote WebDriverorg.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.42.1', revision: '68b415adb11acca4286be45124325cc36cfc4a51', time: '2014-05-29 09:21:55'
System info: host: 'SDGL691', ip: '10.20.20.29', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_67'
Driver info: driver.version: RemoteWebDriver]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.framework.exception.MyException: Error in connecting with Remote WebDriverorg.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.42.1', revision: '68b415adb11acca4286be45124325cc36cfc4a51', time: '2014-05-29 09:21:55'
System info: host: 'SDGL691', ip: '10.20.20.29', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_67'
Driver info: driver.version: RemoteWebDriver
	at com.framework.testtemplate.TestBase.startWebDriver(TestBase.java:116)
	at com.rediff.testcases.HomePageTest.classSetUp(HomePageTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- com.framework.exception.MyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classSetUp -->
        <test-method status="SKIP" signature="HomePageTestSetUp(java.lang.reflect.Method)[pri:0, instance:com.rediff.testcases.HomePageTest@87bd1c]" name="HomePageTestSetUp" is-config="true" duration-ms="0" started-at="2014-11-14T11:50:39Z" finished-at="2014-11-14T11:50:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HomePageTestSetUp -->
        <test-method status="SKIP" signature="verifyBrokenLink()[pri:0, instance:com.rediff.testcases.HomePageTest@87bd1c]" name="verifyBrokenLink" duration-ms="4" started-at="2014-11-14T11:50:39Z" finished-at="2014-11-14T11:50:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyBrokenLink -->
        <test-method status="FAIL" signature="TearDown(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:com.rediff.testcases.HomePageTest@87bd1c]" name="TearDown" is-config="true" duration-ms="0" started-at="2014-11-14T11:50:39Z" finished-at="2014-11-14T11:50:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyBrokenLink status=SKIP method=HomePageTest.verifyBrokenLink()[pri:0, instance:com.rediff.testcases.HomePageTest@87bd1c] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.rediff.testcases.HomePageTest.verifyBrokenLink() throws com.framework.exception.MyException]]>
              </value>
            </param>
          </params>
          <exception class="com.framework.exception.MyException">
            <message>
              <![CDATA[TestBase -> embedScreenShotIntoReport() - null]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.framework.exception.MyException: TestBase -> embedScreenShotIntoReport() - null
	at com.framework.report.CaptureBrowserScreenShot.embedScreenShotIntoReport(CaptureBrowserScreenShot.java:88)
	at com.framework.testtemplate.TestBase.TearDown(TestBase.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- com.framework.exception.MyException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="PASS" signature="stopDriver()[pri:0, instance:com.rediff.testcases.HomePageTest@87bd1c]" name="stopDriver" is-config="true" duration-ms="2" started-at="2014-11-14T11:50:39Z" finished-at="2014-11-14T11:50:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stopDriver -->
      </class> <!-- com.rediff.testcases.HomePageTest -->
    </test> <!-- Rediff WebSite Testing -->
  </suite> <!-- Rediff Mail Execution Suite -->
</testng-results>
